### ISSUE TITLE
Consider using osdn.net instead of sf.net

### ISSUE THREAD

**Issue by okkez** [milter-manager/milter-manager#100]
sf.net がだいぶあやしいので諸々 osdn.net に移行を検討したい。
- osdn.net に既にある機能
  - ML
  - ファイルリリース
  - フォーラム
  - webサイトのホスティング
- osdn.net にまだない機能
  - apt/yum リポジトリをホスティングする機能
    - webサイト用の領域に置けばできるけど。。。

**Comment by okkez** [comment]
* https://osdn.jp/projects/milter-manager/

プロジェクトは作っておいた。

**Comment by kou** [comment]
> sf.net がだいぶあやしい

なにがどう怪しいのか共有してもらえませんか？

移行するかどうかは別にして、パッケージはpackagecloudのOpen Sourceプランがいいんじゃないかと思います。
https://packagecloud.io/pricing の 「Looking for free or open-source plans?」をクリックするとでてきます。

**Comment by okkez** [comment]
> なにがどう怪しいのか共有してもらえませんか？

プロジェクト乗っ取りがあって信用できなくなってます。
度々、ダウンロード用のリンク先が変更されるなどして追従が面倒。
どう変更されたのかが、公式にアナウンスされてなくて手探りで対応しないといけないことがあった。
ダウンロードページのリンクが詐欺っぽいリンクばかりになった。

他にもありそうだけど、自分が「嫌だなぁ、移行先探したいなぁ」と感じたきっかけはこんな感じです。

packagecloud はよさそうですね！

**Comment by kou** [comment]
ありがとうございます。
では、移行先の条件では少なくとも以下の2点を必須にするのがよさそうですね。

  * ダウンロード用のURLが変わらないこと
  * ユーザーがダウンロードページからダウンロードするときに迷わないUIなこと

**Comment by okkez** [comment]
packagecloud.io にコンタクトしてみた。返事待ち。

**Comment by okkez** [comment]
packagecloud.io に milter manager 用のアカウントを作って OSS Plan にしてもらった。

**Comment by okkez** [comment]
利用条件として pacakgecloud.io にリンクを張る必要があるのでリンクを追加しておく。

> In exchange for free packagecloud.io service, we ask that projects link back to us on the website. You can find our logo here: https://packagecloud.io/brand-guidelines

**Comment by okkez** [comment]
そもそも動いていたのか謎だけど Piwik の代替手段を考えないといけない。
osdn.net だと Google Analytics が使えるようだけど、とりあえずいらないのかなぁ？

**Comment by okkez** [comment]
sf.net に置いてある .htaccess にリダイレクト仕込まないといけないかも。

**Comment by kou** [comment]
Piwikは使っていないのでどうなっても構いません。

**Comment by kou** [comment]
「ダウンロードURLが変わらないこと」は大事なこと（他のURLも変わらない方がいいけど）なはずなので、リダイレクトなり現在のユーザーが困らないようにして欲しいです。（一ユーザーとしてもそうだとうれしいです。）

**Comment by okkez** [comment]
* http://milter-manager.sourceforge.net/ -> http://milter-manager.osdn.jp/ は .htaccess で設定できるのでやる
* frs.sf.net にアップロードしてある個々の tarball やパッケージへのアクセスはリダイレクトできない (https://sourceforge.net/projects/milter-manager/files/ へのアクセス)
  * メーリングリストやトップページ等で告知する
  * frs.sf.net でも README.txt というファイルを置けば表示されるようなので何か書いて置いておこう

**Comment by okkez** [comment]
MLのメンバー移行は管理用パスワードの発行がうまくいかなかったので、[サポートに問い合わせ中](https://osdn.net/ticket/browse.php?group_id=1&tid=36811)

**Comment by okkez** [comment]
移行できた。
