### ISSUE TITLE
milter-test-server: add disable timeout option

### ISSUE THREAD

**Issue by okkez** [milter-manager/milter-manager#101]
milter-test-server にはタイムアウトが4つあって、全てを一括で無効にすることができない。

```
  --connection-timeout=SECONDS              Timeout after SECONDS seconds on connecting to a milter.
  --reading-timeout=SECONDS                 Timeout after SECONDS seconds on reading a command.
  --writing-timeout=SECONDS                 Timeout after SECONDS seconds on writing a command.
  --end-of-message-timeout=SECONDS          Timeout after SECONDS seconds on end-of-message command.
```

milter-manager を gdb 経由で実行しているときに milter-test-server 側でタイムアウトによって接続を切られてしまうと、期待通りの動作にならない。
毎回4つオプションを指定すればいいのだけど、面倒なので一括でタイムアウトを無効にするオプションが欲しい。

もしかすると、同様のオプションが milter-test-client や milter-manager 自体にも欲しくなるかもしれない。
#54 の調査にも有用なはず。

**Comment by komainu8** [comment]
プロジェクトをフォークして、ビルド環境を構築中です。
本issueの実装案として現在、思いついた実装概要は以下の通りです。

<pre>
1. 
option_entriesに新規に以下の定義を追加。(オプション名、関数名、Discriptionの内容は後程変更します。)

    {"all-timeout", 0, 0, G_OPTION_ARG_CALLBACK, set_all_timeout_value,
     N_("Discription"), "SECONDS"},

2.
set_all_timeout_value関数を新規に追加。

3.
set_all_timeout_value関数内で以下の値をコマンドライン引数で与えられた値で変更。

connection_timeout
writing_timeout
reading_timeout
end_of_message_timeout
</pre>

上記3で特別な値を設定することで、それぞれのタイムアウトを無効にできるかと思ったのですが、(例えばNULLに設定すると待ち時間が無限になる等) ざっと調査した限りではそのような値はなく、connection_timeout、writing_timeout、reading_timeout、end_of_message_timeoutで設定する秒数だけwaitするように見受けられました。


以下、ご提案なのですが、
タイムアウトを無効にするためには、上記以外の処理に色々手を入れる必要がありそうですが、本issueの目的を考えるにタイムアウトを無効にする必要はなく、一括してタイムアウト値を変更できればよいように思います。

一括してタイムアウト値を変更するオプションを実装するほうが、既存のソースへの変更も少なく対応できそうに思いますので、「タイムアウトを一括で無効」 から 「タイムアウト時間を一括で変更」に内容を変更したほうが良いと思うのですが、いかがでしょうか？

**Comment by okkez** [comment]
それでお願いします！

**Comment by komainu8** [comment]
本issueの内容を実装し、#102 にてpull requestを上げました。
お手数ですが、ご確認をお願いいたします。
