### ISSUE TITLE
http://lists.osdn.me/mailman/listinfo/milter-manager-users-en uses Japanese

### ISSUE THREAD

**Issue by kou** [milter-manager/milter-manager#110]
The list users will not understand Japanese. So they will not be able to subscribe the list.

**Comment by kou** [comment]
"Milter-manager-users-en Archives" like uses https://ja.osdn.net/projects/milter-manager/lists/archive/users-en/ . It also uses Japanese.

**Comment by okkez** [comment]
https://en.osdn.net/projects/milter-manager/lists/archive/users-en/ redirect to https://osdn.net/projects/milter-manager/lists/archive/users-en/

**Comment by okkez** [comment]
I've reported to osdn team https://osdn.net/ticket/browse.php?group_id=1&tid=36778

**Comment by okkez** [comment]
I've changed language configuration for milter-manager-users-en.
