### ISSUE TITLE
Support Rmilter

### ISSUE THREAD

**Issue by kou** [milter-manager/milter-manager#113]
[Rmilter](https://rspamd.com/rmilter/). It can be used as an alternative of SpamAssassin.

Rmilter support is partially implemented. It's available on CentOS 6 and FreeBSD but not available on other platforms.

I hope that the next release includes full Rmilter support.

**Comment by okkez** [comment]
:memo:  
There are no available package on packages.debian.org.
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=813222

But https://rspamd.com/downloads.html distributes deb packages.

https://rspamd.com/downloads.html also distributes rpm packages for CentOS6 and CentOS7.

**Comment by okkez** [comment]
I've added automatic detection for Rmilter.
Need more test before next release.

**Comment by okkez** [comment]
> https://rspamd.com/rmilter/

Use [rspamd_proxy](https://rspamd.com/doc/workers/rspamd_proxy.html) instead.

**Comment by kou** [comment]
We should also support rspamd_proxy.

**Comment by okkez** [comment]
#126

**Comment by okkez** [comment]
Released 2.1.1
