### ISSUE TITLE
Can CentOS7 support newer Ruby versions?

### ISSUE THREAD

**Issue by okkez** [milter-manager/milter-manager#120]
CentOS7 official Ruby pacakge is 2.0.0, but Ruby 2.0.0 is EOL.
We want to upgrade Ruby on CentOS7 without building Ruby RPM for this project such as CentOS6.

**Comment by okkez** [comment]
https://www.softwarecollections.org/en/scls/rhscl/rh-ruby24/

NOTE: Above SCL provides only x86_64 for CentOS6

**Comment by okkez** [comment]
* OK: rh-ruby23 + rh-ruby23-ruby-devel
* NG: rh-ruby24 + rh-ruby24-devel (#132)

**Comment by okkez** [comment]
SCLのパッケージに依存させてしまうと環境変数を調整しないと起動すらできないのがめんどう。
ruby22.specと同じようにするのがてっとり早いけど、その前に #132 を解決しないといけない。

**Comment by kou** [comment]
SCLを使うようにした。
