### ISSUE TITLE
milter-test-server fails to read from unix socket with EAGAIN

### ISSUE THREAD

**Issue by oleksandriegorov** [milter-manager/milter-manager#122]
Hi,
I am trying to enter the basic testing of my milter functionality using milter-test-server, version is 2.1.0
`/usr/bin/milter-test-server -s unix:/var/run/some-milter-milter.sock -r alex.yegorov@whatever.com
status: temporary-failure
elapsed-time: 0.000955 seconds`
This "temporary-failure" in strace (attached it for your reference) occurs at reads:
`read(5, 0xedaa71, 1024)                 = -1 EAGAIN (Resource temporarily unavailable)`
And I cannot get what else to do to troubleshoot.
OS is Centos 6.9, filesystem is ext4
Could you probably help?
Thanks in advance!
[milter-test-server.strace.txt](https://github.com/milter-manager/milter-manager/files/1092733/milter-test-server.strace.txt)

**Comment by okkez** [comment]
What is your milter? Is OSS?
Could you show me your configuration?
Which is your construction?
A: milter-test-server -> milter-manager -> your milter
B: milter-test-server -> your milter

I want to try your milter on my local machine.

Could you try to run your milter using TCP socket?

```
$ milter-test-client -s inet:10025 --daemon # replace your milter
$ milter-test-server -s inet:10025 
```

**Comment by oleksandriegorov** [comment]
Hi, thanks for responding!
My case construction is B: milter-test-server -> my milter.
Unfortunately my milter isn't OSS, however I am sure I could strip specific code from it, test and see if the issue is still replicable. Stay tuned.
As to running milter on a tcp socket - I will give it a try as well and post the results back to this thread.

**Comment by oleksandriegorov** [comment]
My milter did not work either if launched to listen to a tcp socket:
```bash
 /usr/bin/milter-test-server -s inet:10025@69.49.111.15
status: temporary-failure
elapsed-time: 0.000769 seconds
```

Replaced my milter with milter-test-client, launched milter-test-server and that worked:
```bash
XXXXXXX# milter-test-server -s inet:10025 
status: pass
elapsed-time: 0.002 seconds
```

Also tested OSS spfmilter and figured that connection is OK for it in both unix socket and tcp listening mode:
```bash
/usr/bin/milter-test-server -s unix:/var/run/spfmilter/spfmilter.sock
status: pass
elapsed-time: 0.054083 seconds
```

```bash
/usr/bin/milter-test-server -s inet:10026@69.49.111.15
status: pass
elapsed-time: 0.09278 seconds
```

Though stracing milter-test-server does not help me much, it pushes me to thought that I can strace my milter and see if there is anything valuable there. Or I can just check the code of my milter of anything prone to stop responding under certain circumstances.
Stay tuned.

**Comment by oleksandriegorov** [comment]
Next, I noticed that things do not get any further than xxfi_envfrom() in my milter, and it appeared that my milter throws TEMP_FAIL in case client_addr (connecting address) macro cannot be fetched.
Once I added this macro to the list of macros, available for xxfi_envfrom(), milter-test-server was able to talk to my milter and I saw how this connection passes through the milter:
```bash
/usr/bin/milter-test-server -s unix:/var/run/my-milter-milter.sock -r alex.yegorov@anydomain.com --envelope-from-macro=client_addr:69.49.111.16
status: pass
elapsed-time: 0.007251 seconds
```

```bash
 /usr/bin/milter-test-server -s inet:10025@69.49.111.15 -r alex.yegorov@anydomain.com --envelope-from-macro=client_addr:69.49.111.16
status: pass
elapsed-time: 0.008442 seconds
```

So it is important to note, which macros are in-house written milters depend on.
Thank you for your support!
