### ISSUE TITLE
Release 2.1.2

### ISSUE THREAD

**Issue by okkez** [milter-manager/milter-manager#131]
* #128 #130 
* #127 
* #120 

とりあえず、これだけやればリリースできる。

**Comment by okkez** [comment]
Debianのcutter-testing-frameworkがなくなったので milter manager のdebがpbuilderでビルドできなくなってしまった。
うーん、困った。

依存を外してテストを無効にすればビルドできるけど。。。

**Comment by okkez** [comment]
cutter-testing-framework が復活するまでペンディング。

**Comment by kou** [comment]
Is there any progress?
I want a package that includes the fix of #128.

**Comment by okkez** [comment]
Nothing.
I'm waiting for cutter-testing-framework deb package.

**Comment by kou** [comment]
How to enable cutter-testing-framework deb package?
BTW, is it very important than releasing a new version that includes the rspamd fix?

**Comment by okkez** [comment]
> How to enable cutter-testing-framework deb package?

@kenhys handles the issue.

> BTW, is it very important than releasing a new version that includes the rspamd fix?

I cannot say either.
We must update build scripts and dependencies If we don't wait for reviving cutter-testing-framework deb package.
I don't have enough time to release milter-manger in this month.

**Comment by kou** [comment]
@kenhys Is there any progress on cutter-testing-framework deb package?

And can you (or someone) release milter-manager instead of @okkez ?

**Comment by okkez** [comment]
Released without cutter-testing-framework dependency.
