### ISSUE TITLE
"no write channel" error: why?

### ISSUE THREAD

**Issue by princeofnaxos** [milter-manager/milter-manager#133]
milter-manager is reporting "[writer][write][error] no write channel" in the mail log. What is causing this?

**Comment by okkez** [comment]
> Error occurs when request to write.

https://milter-manager.osdn.jp/reference/log-list.html

If you want to know more details, change log level to debug or trace.

https://milter-manager.osdn.jp/reference/configuration.html#configuration.log

**Comment by okkez** [comment]
No response
