### ISSUE TITLE
Broken body after NULL character

### ISSUE THREAD

**Issue by okkez** [milter-manager/milter-manager#135]
https://lists.osdn.me/mailman/archives/milter-manager-users-ja/2018-June/000019.html

**Comment by okkez** [comment]
milter-test-client + milter-test-server だと NULL 文字以降の body が消える。
もらった再現用 milter + milter-test-server でも同様。

**Comment by okkez** [comment]
milter-test-client-libmilter でも同じ。

**Comment by okkez** [comment]
コールバックの定義が以下のようにCのchar(gchar)を使用している。

```c
cb_body (MilterClientContext *context, const gchar *chunk, gsize length,  gpointer user_data)
mlfi_body (SMFICTX *context, unsigned char *data, size_t data_size)
```

Ruby側の実装でも `g_signal_connect` しているだけなのでCのcharを経由してからデータが来るのは同じ。
`length`, `data_size` も NULL 文字までの body の流さになっている様子。

よって、回避策はなさそう。

手元でもMTA(Postfix)を通すと、NULLのあった場所以降に変なデータが付いている現象が再現した。

**Comment by okkez** [comment]
MTA を通しても milter-test-client だと再現しない。
milter-test-client.rb だと再現する。

**Comment by okkez** [comment]
milter-test-client.rb をデバッグモードで動かすと以下のようなログが出て chunk の長さが `40` となるが、これは NULL 文字を含んだ body 全体の長さと一致する。
(テスト用のデータが十分小さいため)

```
[2] [command-decoder][body] <40>
```

**Comment by okkez** [comment]
https://github.com/milter-manager/milter-manager/blob/master/milter/core/milter-command-decoder.c#L786-L802

たぶんここらへんをどうにかすればいい。

そして chunk(buffer) は not NUL-terminated らしい。
https://github.com/avar/sendmail-pmilter/blob/master/doc/milter-protocol.txt#L205

**Comment by okkez** [comment]
gdb で中身を見るとこうなってる。

```
(gdb) p buffer
$2 = (const gchar *) 0x555555f46ef0 "Baaaaaaaaa\r\nbbbbbbbb"
```

**Comment by okkez** [comment]
https://github.com/milter-manager/milter-manager/blob/master/milter/core/milter-decoder.c#L46-L52
で MilterDecoderPrivate の buffer が GString なので NULL-terminated でない文字列を扱うことも意図しているようだけど `milter_decoder_get_buffer` で `buffer->str` しているため NULL-terminate された文字列になってしまっている。
https://developer.gnome.org/glib/stable/glib-Strings.html#glib-Strings.description

原因はこれだと思うけど、直し方まではすぐにはわからなそう。

**Comment by kou** [comment]
データと長さを渡すようにしたので`\0`も扱えるようになった。
