### ISSUE TITLE
Japanese reference document is not installed

### ISSUE THREAD

**Issue by obache** [milter-manager/milter-manager#136]
probably since 1109a6392f809c6f272710e7769df08db0a4e4f2
past gtk-doc.make was custom version with CATALOGS support, not stock version from gtk-doc.

**Comment by okkez** [comment]
Thank you for reporting issue.
I will check this later.

**Comment by okkez** [comment]
Relased 2.1.3.

**Comment by obache** [comment]
maybe fixed to be built, but still not installed with "make install".

**Comment by okkez** [comment]
I've fixed https://github.com/milter-manager/milter-manager/commit/3821b2dac0a6bae672f4bdc181fe2fb515f6014a

@obache Could you check "make install"?
I will release the new version tomorrow if your check is OK.

**Comment by obache** [comment]
https://github.com/milter-manager/milter-manager/blob/3821b2dac0a6bae672f4bdc181fe2fb515f6014a/doc/reference/Makefile.am#L591

no need to handle '' in addition to $(CATALOGS) here, default English version is already installed properly.


OK for others for me, thanks!

But it might better to add CATALOGS support based on up-to-date gtk-doc rule, to remove unwanted index.sgml handling, out-or-source build support, and so on.

**Comment by okkez** [comment]
Thank you for checking. I've released 2.1.4.
