### ISSUE TITLE
ppaのバージョンの付け方を変更してほしい

### ISSUE THREAD

**Issue by znz** [milter-manager/milter-manager#137]
`2.1.4-2~xenial1` や `2.1.4-2~bionic1` のようなバージョンだと `do-release-upgrade` の後に <https://blog.n-z.jp/blog/2019-04-28-xenial-bionic-ppa-downgrade.html> のような感じで適切なバージョンに更新できないので、bionic などではなく ubuntu 公式パッケージで使われているように 18.04 などの数字にしてほしいです。

**Comment by kou** [comment]
変更しました。
