### ISSUE TITLE
Improve Ruby/GLib2 detection on Debian GNU/Linux and Ubuntu

### ISSUE THREAD

**Issue by kou** [milter-manager/milter-manager#141]
`rbgobject.h` is installed into `/usr/lib/x86_64-linux-gnu/ruby/vendor_ruby/2.7.0/rbgobject.h` by `ruby-gnome-dev` package on Debian GNU/Linux and Ubuntu.

It's not related to `Gem::Specification.find_by_name("glib2").full_gem_path` (`"/usr/share/rubygems-integration/2.7.0/gems/glib2-3.4.1"`). So the current Ruby/GLib2 detection doesn't work with `ruby-gnome-dev` package on Debian GNU/Linux and Ubuntu.

**Comment by uwabami** [comment]
Add `CFLAGS += -I$(shell ruby -rrbconfig -e 'print RbConfig::CONFIG["vendorarchdir"]')` in `debian/rules`.

Regards,

**Comment by kou** [comment]
Thanks.

It seems that we can do it automatically by improving https://github.com/milter-manager/milter-manager/blob/master/configure.ac#L379-L411 .

**Comment by kou** [comment]
Done.
