### ISSUE TITLE
Release 2.1.6

### ISSUE THREAD

**Issue by kenhys** [milter-manager/milter-manager#151]

**Comment by kou** [comment]
Tagged and uploaded `.tar.gz` to GitHub Releases and `.rpm` for CentOS 7 to PackageCloud but there are remaining tasks:

  * Build packages for Debian
  * Upload packages for Ubuntu to PPA
  * Build packages for AlmaLinux 8

**Comment by uwabami** [comment]
Please upload gpg sign file: ```milter-manager-2.1.6.tar.gz.asc```

**Comment by kou** [comment]
Released. But there are some problems in 2.1.6.

We should fix them and release a new version.
