### ISSUE TITLE
test/tool/fixtures/ 以下の rrd ファイルが 64bit バイナリなので 32bit 環境 (e.g. i386) では読めず、テストに失敗する。

### ISSUE THREAD

**Issue by uwabami** [milter-manager/milter-manager#199]
表題の通りです。fixtures としてより適切なデータが欲しいですが…。
e.g.:  https://salsa.debian.org/debian/milter-manager/-/jobs/4720523

**Comment by kou** [comment]
たしかに！

ちょっと、32bit環境を積極的に頑張りたくないので32bit環境ではテストを実行しないようにしました。
