### ISSUE TITLE
Ubuntu の ruby-milter-client がエラーになる

### ISSUE THREAD

**Issue by tmtm** [milter-manager/milter-manager#57]
Ubuntu 14.10 で ruby-milter-client をインストールして、require するとエラーになります。

```
% ruby -r milter -e ''
/usr/lib/ruby/vendor_ruby/milter.rb:4:in `load': cannot load such file -- /usr/lib/milter-manager/binding/lib/milter/client.rb (LoadError)
	from /usr/lib/ruby/vendor_ruby/milter.rb:4:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```
`/usr/lib/ruby/vendor_ruby/milter.rb` で `/usr/lib/milter-manager/binding/lib/milter/client.rb` を load してますが、そのファイルはありません。
代わりに `/usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter.rb` があります。

**Comment by okkez** [comment]
すみません。multi architecture 対応で入ったバグです。
次のリリースで直す予定です。
それまでは、/usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter.rb を require するように /usr/lib/ruby/vendor_ruby/milter.rb を直して使ってください。
