### ISSUE TITLE
Milter::Logger の出力に色をつけるかどうかが標準出力に依存している

### ISSUE THREAD

**Issue by tmtm** [milter-manager/milter-manager#58]
Milter::Logger の出力に色をつけるかどうかが標準出力が端末かどうかに依存しています。

1\. ログファイル名を指定しない場合、標準出力に色付きで出力されます。
```
% ruby -rmilter -e 'Milter::Logger.message "hoge"'
```

2\. 標準出力がファイルにリダイレクトされていると色はつきません。
```
% ruby -rmilter -e 'Milter::Logger.message "hoge"' > /tmp/log
```

3\. ログファイル名を指定しても、標準出力が端末だと色がつきます。
```
% ruby -rmilter -e 'Milter::Logger.default.path="/tmp/log"; Milter::Logger.message "hoge"'
```

4\. ログファイル名を指定して、標準出力をリダイレクトすると色がつきません。
```
% ruby -rmilter -e 'Milter::Logger.default.path="/tmp/log"; Milter::Logger.message "hoge"' > /dev/null
```

ログに色を付けるかどうかは標準出力が端末かどうかではなく、ログ出力先が端末かどうかで判断すべきだと思います。

**Comment by kou** [comment]
その通りなのでそうしました！
