### ISSUE TITLE
Stop to bundle test-unit for Debian and Ubuntu

### ISSUE THREAD

**Issue by okkez** [milter-manager/milter-manager#63]
Debian や Ubuntu では test-unit をバンドルするのをやめたい。
理由は
- test-unit は安定しているので無理してHEADを使わなくてもよい
- Debian や Ubuntu のオフィシャルパッケージにするなら ruby-test-unit というパッケージが使える
- メンテナンスコストを下げたい

CentOSではどうするのか検討が必要。

**Comment by uwabami** [comment]
@okkez #112 に関連して，既に Debian/Ubuntu 側では対応できているのでは？

**Comment by okkez** [comment]
元々パッケージには含まれてませんでした。
tarball から排除できればしたいなーくらいの気持ちだったのですが、対応不要そうなので閉じます。
