### ISSUE TITLE
Release 2.0.6

### ISSUE THREAD

**Issue by okkez** [milter-manager/milter-manager#64]
11月にmilter manager 2.0.6 をリリースする。
いくつかやりたいことがあるのでここにまとめながら、作業を進める。

[リリースのための文書](https://github.com/milter-manager/milter-manager/blob/master/doc/release.rd.ja)

* [x] event_loop_backendの項目にGLibバックエンドの場合の制限事項を記載する。下のコメントを参考にする。ドキュメントの形式はRD形式。
* [x] Ubuntu 15.10 サポートを追加する。ドキュメントも更新する。
* [x] Ubuntu 14.10 サポートを切る。ドキュメントも更新する。
* [x] CentOS6向けにバンドルしているRubyを2.2.3に上げる
* [x] #52 の動作確認をして問題なければ閉じる
* [x] #60 の動作確認をして問題なければ閉じる
* [ ] TravisCIのRuby2.2向けビルドが壊れている
* [x] systemd 対応について groonga を参考にして検討する
  * Debian系は今回は断念する
* [x] NEWS, NEWS.ja を書く
  * Debian Wheezy 向けのパッケージはこれで最後です、とリリースノートに書き、リリースしたら、その後すぐにwheezyサポートを切っておく
* [x] 日本語、英語のリリースメールの下書きを書く
* [x] コンパイラのwarningを潰す
  * 旧環境でのビルドは壊さないようにする

**Comment by okkez** [comment]
skypeですとうさんに教えてもらった制限事項。
milter managerのドキュメントに書いていないので書いておく。

```text
milter managerのやつなんですけど、GLibバックエンドだと通信回数に上限があるんですよ。
 milter managerは1プロセスあたりの同時処理性能を高めるためにイベント駆動ベースのモデルで実装しています。
 で、イベント駆動のモデルだとコールバックを登録するんですが、そのコールバックごとにIDが発行されます。
 GLibバックエンドのときはGMainContextを使うんですけど、IDは符号なし32bit整数だったかそういうサイズの数値をインクリメントしながら発行するんですね。
 で、それが上限に達するとGLibはエラー扱いにするんですよ。
 古いIDを再利用とかはしないんですね。
 なので、GLibバックエンドだと通信回数に上限があるんです。
 libevの方はそういう制限はないです。
```

**Comment by cosmo0920** [comment]
> - [ ] コンパイラのwarningを潰す
> 
>    - 旧環境でのビルドは壊さないようにする


こちら覗いてみましたが、#65 以外にmilter-manager側で治せるのは見当たりませんでした。
glib2とバンドルされたlibevでもWarningが出ていますが、これはそれぞれglib2とlibevの問題に思います。

**Comment by okkez** [comment]
わかりました。ありがとうございます。
あとは、リストの上から順番にやっていってください。
11/13くらいまでにsystemd対応の検討までは終わっていたいなぁと思っています。

**Comment by cosmo0920** [comment]
#67 でGLibバックエンドの制限事項を記載したドキュメントを追加してみました。

* milter managerは1プロセスあたりの同時処理性能を高めるためにイベント駆動ベースのモデルで実装していること
* GLibを用いたイベント駆動のモデルだとコールバックを登録し、コールバックの登録数に上限があること
* コールバックの登録数の上限が結果的に通信回数に上限を設けてしまうこと
* この制限はglibバックエンドのみであること

を記載しました。

**Comment by cosmo0920** [comment]
> - [ ] Ubuntu 14.10 サポートを切る。ドキュメントも更新する。

Ubuntu 13.10 (Saucy) のサポートも切ってドキュメントも更新すると良さそうです。

**Comment by okkez** [comment]
はい、お願いします！

**Comment by cosmo0920** [comment]
> - [ ]  Ubuntu 14.10 サポートを切る。ドキュメントも更新する。

こちらは Ubuntu 15.10 (Wily) の作業が完了してから着手するほうが良さそうです。いくつかコンフリクトしそうな箇所があります。

**Comment by cosmo0920** [comment]
CentOS6でRuby 2.2.3をバンドルするのを試してみています。

https://github.com/cosmo0920/milter-manager/tree/bundle-ruby223-in-centos6
でRuby 2.2.3のrpmのビルドは出来るようになったのですが、バンドルされているlibevのリンクが出来ないです。。

```log
...
  CC       milter-manager.o
  CCLD     milter-manager
/usr/bin/ld: warning: libev.so.4, needed by ../milter/core/.libs/libmilter-core.so, not found (try using -rpath or -rpath-link)
../milter/core/.libs/libmilter-core.so: undefined reference to `ev_set_userdata'
../milter/core/.libs/libmilter-core.so: undefined reference to `ev_async_stop'
../milter/core/.libs/libmilter-core.so: undefined reference to `ev_async_start'
../milter/core/.libs/libmilter-core.so: undefined reference to `ev_default_loop'
../milter/core/.libs/libmilter-core.so: undefined reference to `ev_loop_new'
../milter/core/.libs/libmilter-core.so: undefined reference to `ev_idle_stop'
../milter/core/.libs/libmilter-core.so: undefined reference to `ev_set_loop_release_cb'
../milter/core/.libs/libmilter-core.so: undefined reference to `ev_child_stop'
../milter/core/.libs/libmilter-core.so: undefined reference to `ev_io_start'
../milter/core/.libs/libmilter-core.so: undefined reference to `ev_child_start'
../milter/core/.libs/libmilter-core.so: undefined reference to `ev_async_send'
../milter/core/.libs/libmilter-core.so: undefined reference to `ev_timer_stop'
../milter/core/.libs/libmilter-core.so: undefined reference to `ev_io_stop'
../milter/core/.libs/libmilter-core.so: undefined reference to `ev_loop_destroy'
../milter/core/.libs/libmilter-core.so: undefined reference to `ev_idle_start'
../milter/core/.libs/libmilter-core.so: undefined reference to `ev_run'
../milter/core/.libs/libmilter-core.so: undefined reference to `ev_timer_start'
../milter/core/.libs/libmilter-core.so: undefined reference to `ev_userdata'
../milter/core/.libs/libmilter-core.so: undefined reference to `ev_break'
collect2: ld returned 1 exit status
make[2]: *** [milter-manager] Error 1
make[2]: Leaving directory `/home/milter-manager-build/rpm/BUILD/milter-manager-2.0.5/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/milter-manager-build/rpm/BUILD/milter-manager-2.0.5'
make: *** [all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.iLzACT (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.iLzACT (%build)
xargs: rpmlint: No such file or directory
cp: `/var/lib/chroot/centos-6-i386/home/milter-manager-build/rpm/RPMS/i386/*.rpm' を stat できません: そのようなファイルやディレクトリはありません
Failed cp -p /var/lib/chroot/centos-6-i386/home/milter-manager-build/rpm/RPMS/i386/*.rpm centos/6/stable/i386/Packages
make: *** [build-in-chroot] エラー 1
```

**Comment by okkez** [comment]
Ruby2.1.5のままだとどうですか？

**Comment by okkez** [comment]
あ、[doc/configuration.rd](https://github.com/milter-manager/milter-manager/blob/master/doc/configuration.rd#L640)と[dco/configuration.rd.ja](https://github.com/milter-manager/milter-manager/blob/master/doc/configuration.rd.ja#L634)にもevent_loop_backendの説明があるので制限事項を書いておいてください。むしろ、こっちに説明がないのが問題でした。

**Comment by okkez** [comment]
doc/milter-manager.rd と doc/milter-manager.rd.ja には `--event-loop-backend` の説明自体が無いので追加しておいて欲しいです。
このファイルに追加しておくとmanにも載ります。

**Comment by cosmo0920** [comment]
> Ruby2.1.5のままだとどうですか？

同じく https://github.com/milter-manager/milter-manager/issues/64#issuecomment-154236886 のエラーで止まってしまいます。

**Comment by cosmo0920** [comment]
chroot環境下でのmilter-managerのビルドログをとってみました。
https://gist.github.com/cosmo0920/b30b96fd149fea98032f
libev.so.4が見つからないと言われています。。

**Comment by okkez** [comment]
ビルドエラーは、週末に見れたら見るのでドキュメント関連をやっておいてください。

> あ、doc/configuration.rdとdco/configuration.rd.jaにもevent_loop_backendの説明があるので制限事項を書いておいてください。むしろ、こっちに説明がないのが問題でした。
> doc/milter-manager.rd と doc/milter-manager.rd.ja には --event-loop-backend の説明自体が無いので追加しておいて欲しいです。
> このファイルに追加しておくとmanにも載ります。

**Comment by cosmo0920** [comment]
Ruby 2.2.3をバンドルするようにしたプルリクエスト https://github.com/milter-manager/milter-manager/pull/72 を投げました。こちらのchroot CentOS 6環境では Ruby 2.2.3のRPMとインストールができることを確認しています。

> ビルドエラーは、週末に見れたら見るのでドキュメント関連をやっておいてください。

わかりました！

**Comment by okkez** [comment]
rpmbuildしたときだけうまくビルドできないということがわかりました。
ふつうに `./configure && make` した場合は libev.so.4 は見つかります。

あと rpmbuild したときも libev 自体のビルドは成功していて libev.so.4 も作成されている。

**Comment by okkez** [comment]
chroot して rpm/BUILD/milter-manager-2.0.5 以下を確認。

```text
$ ldd milter/core/.libs/libmilter-core.so
        linux-gate.so.1 =>  (0xf77a8000)
        libgobject-2.0.so.0 => /lib/libgobject-2.0.so.0 (0xf769a000)
        libgmodule-2.0.so.0 => /lib/libgmodule-2.0.so.0 (0xf7696000)
        libgthread-2.0.so.0 => /lib/libgthread-2.0.so.0 (0xf7691000)
        librt.so.1 => /lib/librt.so.1 (0xf7688000)
        libglib-2.0.so.0 => /lib/libglib-2.0.so.0 (0xf756a000)
        libev.so.4 => not found
        libm.so.6 => /lib/libm.so.6 (0xf7540000)
        libpthread.so.0 => /lib/libpthread.so.0 (0xf7525000)
        libc.so.6 => /lib/libc.so.6 (0xf738e000)
        libdl.so.2 => /lib/libdl.so.2 (0xf7388000)
        /lib/ld-linux.so.2 (0x565a8000)
```

なのでその場で `make LD_LIBRARY_PATH=/home/milter-manager-build/rpm/BUILD/milter-manager-2.0.5/libev-4.19/.libs/` したらビルドできた。

/tmp 以下で適当にビルドしたやつだとこうなっていた。

```text
$ ldd /tmp/x/milter-manager-2.0.5/milter/core/.libs/libmilter-core.so
        linux-gate.so.1 =>  (0xf7762000)
        libgobject-2.0.so.0 => /lib/libgobject-2.0.so.0 (0xf765c000)
        libgmodule-2.0.so.0 => /lib/libgmodule-2.0.so.0 (0xf7658000)
        libgthread-2.0.so.0 => /lib/libgthread-2.0.so.0 (0xf7653000)
        librt.so.1 => /lib/librt.so.1 (0xf764a000)
        libglib-2.0.so.0 => /lib/libglib-2.0.so.0 (0xf752c000)
        libev.so.4 => /tmp/x/milter-manager-2.0.5/libev-4.19/.libs/libev.so.4 (0xf7520000)
        libm.so.6 => /lib/libm.so.6 (0xf74f6000)
        libpthread.so.0 => /lib/libpthread.so.0 (0xf74db000)
        libc.so.6 => /lib/libc.so.6 (0xf7344000)
        libdl.so.2 => /lib/libdl.so.2 (0xf733e000)
        /lib/ld-linux.so.2 (0x56589000)
```

**Comment by okkez** [comment]
当然ながら、以前ビルドできていた libev-4.15 をバンドルしている milter-manager-2.0.5 は RPM をビルドできた。

**Comment by okkez** [comment]
たぶん libev-4.19 に上げたことか libev を必須にしたことが影響している気がする。
今日、調べる時間はない。

**Comment by okkez** [comment]
いやー、やっぱり↑は関係なさそう。

**Comment by cosmo0920** [comment]
SystemdのUnitファイルをGroongaのものを参考にしつつ書いてみました。

```ini
[Unit]
Description=milter-manager server daemon
After=syslog.target network.target auditd.service

[Service]
PIDFile=/var/run/milter-manager/milter-manager.pid
User=milter-manager
Group=milter-manager
ExecStart=/usr/sbin/milter-manager $OPTIONS
ExecReload=/bin/kill -HUP $MAINPID

[Install]
WantedBy=multi-user.target
```

こんな感じになりそうです。（Systemdの環境を持っていないので試せていない）

**Comment by cosmo0920** [comment]
上のUnitファイルを

```diff
-ExecStart=/usr/sbin/milter-manager $OPTIONS
+ExecStart=/usr/bin/milter-manager $OPTIONS
```

してArch Linuxでパッケージを作って試した。(Arch Linuxではsbindirが`/usr/bin`のため。)

* 使用した[PKGBUILD](https://github.com/cosmo0920/AUR-milter-manager/blob/868151e48d80a2294eb4855643385b179ef52430/milter-manager/PKGBUILD) 

ログ：

```log
$ sudo systemctl status milter-manager -l
* milter-manager.service - milter-manager server daemon
   Loaded: loaded (/usr/lib/systemd/system/milter-manager.service; disabled; vendor preset: disabled)
   Active: active (running) since Thu 2015-11-12 02:15:20 UTC; 28s ago
 Main PID: 28491 (milter-manager)
   CGroup: /system.slice/milter-manager.service
           `-28491 /usr/bin/milter-manager
```

`milter-manager` ユーザーとグループで動いてはいる様子。 `@libsystemd 227`

**Comment by cosmo0920** [comment]
systemdに対応させる予定のディストリビューションはひとまずCentOS7 とDebian jessie以上向けでしょうか？（とりあえずArhc Linuxで動かしてみたのはディストリ独自のパッチを当てていないので何か問題が起きた時に調査しやすいかなと思ったためです）

**Comment by okkez** [comment]
そうですね。それでお願いします。

**Comment by cosmo0920** [comment]
そういえば、pbuilderでアレコレするやつはDebian jessieだとstretchも含めて動くようなんですが、UbuntuではWilyでも若干debian-keyringが古いのでdebのビルドはUbuntuでは厳しそうです。。

**Comment by okkez** [comment]
なるほどー。Ubuntu辛いですねー。
lxcでjessieのコンテナ作ってその上でpbuilderとかですかね。

**Comment by cosmo0920** [comment]
はっ、その手が…！

**Comment by cosmo0920** [comment]
あとUbuntuのkeyringが必要なので `ubuntu-keyring` パッケージがpbuilderを使う時には必要ですね。

**Comment by okkez** [comment]
release.rd.ja に書いておいてください。

**Comment by cosmo0920** [comment]
pbuilderでdebを作っているとjessieのdebootstrapではWilyはサポートされていない壁にぶち当たった。

```log
I: pbuilder-time-stamp: 1447410711
W: /root/.pbuilderrc does not exist
I: Distribution is wily.
I: Current time: Fri Nov 13 19:31:51 JST 2015
I: pbuilder-time-stamp: 1447410711
I: Building the build environment
I: running debootstrap
/usr/sbin/debootstrap
E: No such script: /usr/share/debootstrap/scripts/wily
E: debootstrap failed
W: Aborting with an error
I: cleaning the build env 
I: removing directory /var/cache/pbuilder/build//16835 and its subdirectories
Failed sudo pbuilder --create --distribution wily --architecture i386 --basetgz /var/cache/pbuilder/wily-i386-base.tgz --aptcache /var/cache/pbuilder/aptcache/wily-i386 --components main universe --mirror http://jp.archive.ubuntu.com/ubuntu --othermirror deb http://jp.archive.ubuntu.com/ubuntu wily-security main universe --debootstrapopts --keyring=/usr/share/keyrings/ubuntu-archive-keyring.gpg
Makefile:601: recipe for target 'build' failed
make: *** [build] Error 1
```

ちなみにsidならwily用のスクリプトが存在する。https://packages.debian.org/ja/sid/all/debootstrap/filelist

**Comment by okkez** [comment]
昨日の夜ビルドしていたら sid だとなぜか vivid のビルドでこけていた。。。

**Comment by cosmo0920** [comment]
Debian jessie以上向けのSystemdのUnitは以下のようにすると良さそう。 
#81 のCentOS用と違ってUser/Groupがroot。

```ini
[Unit]
Description=milter-manager server daemon
After=syslog.target network-online.target

[Service]
User=root
Group=root
ExecStart=/usr/sbin/milter-manager $OPTIONS --pid-file "/var/run/milter-manager/milter-manager.pid"
ExecReload=/bin/kill -HUP $MAINPID

[Install]
WantedBy=multi-user.target
```

`sudo systemctl start milter-manager`で動作する。

```log
$ sudo systemctl status milter-manager.service -l
● milter-manager.service - milter-manager server daemon
   Loaded: loaded (/usr/lib/systemd/system/milter-manager.service; disabled)
   Active: active (running) since Wed 2015-11-25 06:14:04 UTC; 1s ago
 Main PID: 7533 (milter-manager)
   CGroup: /system.slice/milter-manager.service
           ├─7533 /usr/sbin/milter-manager --pid-file /var/run/milter-manager/milter-manager.pid
           └─7537 /usr/sbin/milter-manager --pid-file /var/run/milter-manager/milter-manager.pid
```

`milter-manager` ユーザーとグループをそれぞれUnitのUserとGroupへ指定すると、

```log
$ sudo systemctl status milter-manager.service -l
● milter-manager.service - milter-manager server daemon
   Loaded: loaded (/usr/lib/systemd/system/milter-manager.service; disabled)
   Active: active (running) since Wed 2015-11-25 06:09:45 UTC; 2s ago
 Main PID: 7480 (milter-manager)
   CGroup: /system.slice/milter-manager.service
           ├─7480 /usr/sbin/milter-manager --pid-file /var/run/milter-manager/milter-manager.pid
           └─7484 /usr/sbin/milter-manager --pid-file /var/run/milter-manager/milter-manager.pid

Nov 25 06:09:45 debian-8 milter-manager[7480]: [2015-11-25T06:09:45.691839Z]: [client][error][unix] failed to change UNIX socket group: </run/milter-manager/milter-manager.sock>: <mail>: Operation not permitted
Nov 25 06:09:45 debian-8 milter-manager[7480]: [client][error][unix] failed to change UNIX socket group: </run/milter-manager/milter-manager.sock>: <mail>: Operation not permitted
Nov 25 06:09:45 debian-8 milter-manager[7480]: milter-manager error: failed to change UNIX socket group: </run/milter-manager/milter-manager.sock>: <mail>: Operation not permitted
```

となってしまうのでユーザーとグルーブへ `milter-manager` とするのは一旦諦める。

**Comment by cosmo0920** [comment]
SystemdのUnitファイルは https://github.com/milter-manager/milter-manager/issues/64#issuecomment-159504887 で良さそうだけれどsystemdのserviceファイルをdebに含める方法がわからない…。

**Comment by cosmo0920** [comment]
ひとまず作成したDebian jessie以上向けのUnitファイルを https://github.com/milter-manager/milter-manager/compare/master...cosmo0920:add-systemd-file-for-debian へコミットした。

**Comment by uwabami** [comment]
see dh_systemd_enable and dh_systemd_start

**Comment by cosmo0920** [comment]
> see dh_systemd_enable and dh_systemd_start

Thanks! I'll check it later!

**Comment by okkez** [comment]
CentOS6 でパッケージ名の後の方に i686 って付くのはそのままでいきたい。
i386 なパッケージを入れているところで i686 なパッケージにアップグレードできることを確認する必要がある。
もし何か問題があれば、リリースメールやドキュメントにアップグレード方法を書く。

**Comment by okkez** [comment]
CentOS6 i386 のパッケージ名については問題ない。

**Comment by okkez** [comment]
done!
