### ISSUE TITLE
Consider that Ubuntu apt repository to launchpad PPA

### ISSUE THREAD

**Issue by okkez** [milter-manager/milter-manager#85]
Ubuntu 用の APT リポジトリを launchpad の PPA に移行することを検討する。

**Comment by okkez** [comment]
結論としては、移行しない。

理由。

* アップロードしてから結果がわかるまでに時間がかかりすぎる
* 手元で pbuilder + tmpfs でビルドした方が圧倒的に速い
* アップロードに成功したように見えても、失敗していることがあって失敗に気付けない

**Comment by cosmo0920** [comment]
> アップロードに成功したように見えても、失敗していることがあって失敗に気付けない

アップロードに成功するとメールが飛んでくるんですが、それでは不足ですか？

**Comment by okkez** [comment]
> アップロードに成功するとメールが飛んでくるんですが、それでは不足ですか？

不足していると思いました。
何か失敗していたらできるだけ早く気付きたいのですが、気付く方法がないし、失敗した原因もわからないやつがあるので辛いなぁ、と。

**Comment by kou** [comment]
Mroongaでは使っていますが、失敗してもメールがきて、Webからビルドログを確認できましたよ。
特になにか設定しなくてもきていますけどねぇ。

**Comment by kou** [comment]
Mroongaの例：
https://launchpad.net/~groonga/+archive/ubuntu/ppa/+build/8908688
の
https://launchpadlibrarian.net/235565214/buildlog_ubuntu-trusty-amd64.mroonga-5.6_5.12-2~trusty1_BUILDING.txt.gz

**Comment by okkez** [comment]
自分のアカウント配下でもう一度試してみた。

* 変なところにアップロードしたら通知が来た（以前はこれが来なかった気がする）
* アップロードに成功したら通知が来た
* ビルドに成功しても通知は来ない（便りがないのは良い報せ）
* 10分くらい？でビルドできてた。

以前試したときは、色々間違っていたのではないか疑惑。

**Comment by okkez** [comment]
スクリプトを入れて試したらちゃんとビルドできたのでクローズ。
