### ISSUE TITLE
/etc/default/clamav-milter がない

### ISSUE THREAD

**Issue by znz** [milter-manager/milter-manager#90]
http://milter-manager.sourceforge.net/reference/ja/install-to-debian.html や http://milter-manager.sourceforge.net/reference/ja/install-to-ubuntu.html に `/etc/default/clamav-milter` の `SOCKET_RWGROUP=postfix` についての記述がありますが、確認してみたところ、Debian では wheezy にも jessie にも `/etc/default/clamav-milter` は存在しないようです。
Ubuntu では precise と trusty にはあったのですが、wily には存在しませんでした。(vivid は確認していません。)

設定を変更しなくても `/var/run/clamav/clamav-milter.ctl` が owner も group も clamav で、パーミッションは `srw-rw-rw-` になっていて、other にも読み書き権限があるので、`milter-manager` との連携自体は問題なく動いているようです。

**Comment by kou** [comment]
あるときからclamav-milterを含むClamAV関連のソフトウェアの設定ファイルが一本化されたので、そのときから変わったんだと思います。ClamAV関連のソフトウェアはセキュリティーアップデートで古いディストリビューションでも更新されていくので。

ということで、ドキュメントを修正しました。
