### ISSUE TITLE
/var/spool/postfix/milter-manager がない

### ISSUE THREAD

**Issue by znz** [milter-manager/milter-manager#91]
Debian や Ubuntu で milter-manager 2.0.7-1 を新規インストールすると `/var/spool/postfix/milter-manager` が存在しないため、 http://milter-manager.sourceforge.net/reference/ja/install-to-debian.html や http://milter-manager.sourceforge.net/reference/ja/install-to-ubuntu.html の通りに設定しても `Failed to connect to unix:/var/spool/postfix/milter-manager/milter-manager.sock: No such file or directory` になります。

関連しそうな変更を探してみたところ、 https://github.com/milter-manager/milter-manager/commit/d636147f41f1cf0a3b406b34eb48557d4e7a02b4 で `package/debian/milter-manager.dirs` が削除されているのが問題のように思いました。

**Comment by kou** [comment]
`/var/spool/postfix/milter-manager/milter-manager.sock`にソケットを作るのはデフォルトの設定ではないので、`/var/spool/postfix/milter-manager/`はユーザーに作成してもらうようにドキュメントを修正しました。
