### ISSUE TITLE
2.0.8 リリース

### ISSUE THREAD

**Issue by okkez** [milter-manager/milter-manager#93]
Ubuntu16.04もリリースされたので milter manager 2.0.8 をリリースしたい。

* [x] CentOS7 対応
  * パッケージを作るようにはしたけど、動作確認をした記憶がない
  * CentOS7向けにはRubyをバンドルしない予定だけど、どう実装したのか記憶がない
* [x] systemd 対応
  * 対応できているはずだけど、どのOSでどこまで対応できているのか確認していない
  * ドキュメント書いた記憶がない
* [x] Ubuntu 16.04 対応
  * パッケージを作れるようにはしたけど、テストしていない
  * ドキュメントも書く必要がある
* [x] Ubuntu 向けパッケージは launchpad.net に置くようにする
  * コードは書いて、動くようにはした
    * milter-manager-2.0.8-1~wily1 ではなく milter-manager-2.0.8-2~wily1 にしてるのはなぜ？
  * ローカルで Ubuntu 向けにビルドする仕組みを消す？残しておいても害はない？
* [x] CentOS5 のサポートを切る
  * パッケージは作らなくしたけど、リポジトリの更新が走る気がする
* [x] CentOS6 用にバンドルしているRubyのバージョンを2.2.5に上げる
  * 2.3にするとはまりそうなので
* [ ] release.rd.ja をちゃんと書く
* [x] CentOS6 で 2.0.5 から 2.0.8 へ更新できるようにする
  * 修正はしたつもりだけど、テストがまだ

全体的にパッケージのテストができてない気がするので、リリースするのに不安がある状態です。

**Comment by okkez** [comment]
@kenhys お願いします。

**Comment by kenhys** [comment]
まずはNEWS.jaを書いた。NEWS(en)はまだ。

**Comment by ohkubo** [comment]
> CentOS7向けにはRubyをバンドルしない予定だけど、どう実装したのか記憶がない

この辺でしょうか。

https://github.com/milter-manager/milter-manager/blob/master/package/rpm/centos/milter-manager.spec.in#L1-L11

ところで、 CentOS 7 のサポート・ CentOS 5 の Drop は [2.0.5 で告知済み](http://milter-manager.sourceforge.net/reference/ja/news.html#news.release-2-0-5)のようですね。

**Comment by ohkubo** [comment]
バンドル、となるとこちらの方かもしれません。

https://github.com/milter-manager/milter-manager/blob/master/package/yum/build-rpm.sh#L142-L150

**Comment by kenhys** [comment]
wheezyってまだサポートするんでしたっけ？

**Comment by okkez** [comment]
> wheezyってまだサポートするんでしたっけ？

old stable になってから1回リリースしたら終わりです。
stretch がリリースされたあと2.0.6,2.0.7を出しているのでもう切っていいです。

**Comment by kenhys** [comment]
ではそうしましょう。> wheezyの件。

**Comment by kenhys** [comment]
TODO: @okkezさんに https://launchpad.net/~milter-manager のteamにいれてもらう。

**Comment by kenhys** [comment]
> CentOS5 のサポートを切る
>     パッケージは作らなくしたけど、リポジトリの更新が走る気がする

sign-rpm.shとupdate-repository.shに手をいれたので、CentOS 5で更新が走らないようになった。

**Comment by kenhys** [comment]
パッケージを準備するところまではたどりつけたが、動作確認まで手がまわってない。

**Comment by okkez** [comment]
CentOS7向けにシンボリックリンクが必要だった。

```text
$ cd package/yum/centos/7
$ ln -s stable/x86_64 x86_64
$ ln -s stable/repodata repodata
```

**Comment by okkez** [comment]
CentOS7 の systemd 対応でいくつか問題ありそう。

* /etc/init.d/milter-manager が残っている
  * 残っていると service コマンド経由で使われてしまうっぽいのでよろしくない
* `systemctl enable milter-manager.service` が実行されていないのでenabledにならないけど、他のmilterはdisabledのまま
  * 要検討だが、自動起動させるようにしていい気がしている
* CentOS7 の場合でも `chkconfig --add` が実行されてしまっている
  * `%pre` `%post` のあたりは調べて整理しないといけない

**Comment by okkez** [comment]
CentOS6, 7向けにパッケージに含まれるファイルを整理して、`%post`などをsystemd向けにちゃんと書くようにした。

**Comment by okkez** [comment]
> systemctl enable milter-manager.service が実行されていないのでenabledにならないけど、他のmilterはdisabledのまま 

`%systemd_post` だとシステムの設定に従って enabled にするかどうか決まるので milter-manager は disabled のままなのが設定通り。

**Comment by okkez** [comment]
Ubuntu だと precise, trusty は upstart で wily, xenial は systemd
Debian だと jessie 以降は systemd になっている。

**Comment by okkez** [comment]
debパッケージだと init script と systemd の unit ファイルの両方が入っているんだな。
パッケージ分けているのかと思ったけどそんなことはなかった。
precise と trusty に unit ファイルを入れないようにしてやればよさそう。

**Comment by kenhys** [comment]
6/9にTom Hendrikxさんがxenial 16.04で試してくれて(sf.netにまだ該当メールはアーカイブされてない) syslogに重複メッセージがでるのがどうにかならない？とメールをくれた。
systemd-sysv経由するとそうなるっぽい。
* xenial では発生する
* 2.0.7 & 2.0.8 nightly on trustyだと発生しない

**Comment by okkez** [comment]
Systemd 対応。

* [ ] jessie
* [ ] stretch
* [ ] sid
* [ ] precise
* [ ] trusty
* [ ] wily
* [ ] xenial

**Comment by okkez** [comment]
Systemd 対応の確認ができた。ついでに sid だけ sysvinit-core を入れて動かしてみたが、特に問題なかった。

**Comment by okkez** [comment]
`debian/milter-manager.dirs` が残ってて変なパッケージを作っていたので `debian/milter-manager.tmpfile` に変えて jessie だけ動いていることを確認した。

**Comment by okkez** [comment]
CentOSでのmilter自動検出もOKになったのでdone
