### ISSUE TITLE
Load configuration from /etc/default/milter-manager properly

### ISSUE THREAD

**Issue by okkez** [milter-manager/milter-manager#97]
/usr/sbin/milter-manager cannot load configuration from environment variables.
We cannot apply configuration via /etc/default/milter-manager when run /usr/sbin/milter-manager via systemd service file.

On the other hand, /etc/init.d/milter-manager can load configuration from /etc/default/milter-manager.

**Comment by kou** [comment]
[`EnvironmentFile`](https://www.freedesktop.org/software/systemd/man/systemd.exec.html) may help you. [Groonga uses it](https://github.com/groonga/groonga/blob/master/packages/debian/groonga-httpd.service#L10).

**Comment by okkez** [comment]
We've used EnvironmentFile already.
https://github.com/milter-manager/milter-manager/blob/master/package/debian/milter-manager.service#L8

I think we need to implement that /usr/sbin/milter-manager consider environment variables.
In https://github.com/milter-manager/milter-manager/blob/master/milter/manager/milter-manager-main.c#L114

**Comment by kou** [comment]
Groonga refers environment variables in `ExecStart`: https://github.com/groonga/groonga/blob/master/packages/debian/groonga-server-gqtp.service#L11

Default file: https://github.com/groonga/groonga/blob/master/packages/debian/groonga-server-gqtp.default
