### ISSUE TITLE
CentOS7を再起動するとmilter-managerのプロセスの起動に失敗する

### ISSUE THREAD

**Issue by komainu8** [milter-manager/milter-manager#98]
CentOS7でmilter-managerをインストール後再起動すると、milter-managerのプロセス起動に失敗します。

/var/log/messageには、以下のログが記録されており、以下のログから、再起動後に「/var/run/milter-manager/milter-manager.sock」が存在しないことが原因と考えられます。

<pre>
-----------------------------------------------------------------------------------------------
Jul  4 21:50:12 localhost milter-manager: failed to listen: failed to bind(): un
ix:/var/run/milter-manager/milter-manager.sock: そのようなファイルやディレクトリ
はありません
Jul  4 21:50:12 localhost systemd: milter-manager.service: main process exited,
code=exited, status=1/FAILURE
Jul  4 21:50:12 localhost systemd: Unit milter-manager.service entered failed st
ate.
Jul  4 21:50:12 localhost systemd: milter-manager.service failed.
Jul  4 21:50:56 localhost clamd: SelfCheck: Database status OK.
-----------------------------------------------------------------------------------------------
</pre>

発生環境は以下の通りです。

<pre> 
OS：CentOS 7.2.1511 (Core) x86_64 minimalISOにてインストール
      ※Windows10 Hyper-v上で動作させています。
      yum updateは実施済みです。

・milter-manager 2.0.9
</pre>

**Comment by komainu8** [comment]
CentOS７から/var/runはtmpfsでマウントされており、OS起動時に/var/run配下のディレクトリとファイルは消去されてしまうため、/var/run/milter-manager/milter-manager.sockが作成できず、プロセスの起動に失敗します。

したがって、OS起動時に/var/run配下にmilter-managerディレクトリを作成すれば本問題は解決できそうです。

**Comment by komainu8** [comment]
解決策として以下の2案があります。

1. /etc/tmpfiles.d 以下に設定ファイルを作成し、OS起動時に作成しておきたいディレクトリを指定する。
2.milter-managerのserviceファイル内のExecStartPreでディレクトリを作成する。

2の方法であれば、既存の枠組みの中で解決できるため、修正にかかるコストも少なく、1より良い解決策と思います。

**Comment by komainu8** [comment]
実際に上記2案について、問題が解決するか試してみました。
1.問題が解決しました。
2./var/run配下にディレクトリを作成する権限がなく、問題が解決しませんでした。

<pre>
1./etc/tmpfiles.d 以下に設定ファイルを作成し、OS起動時に作成しておきたいディレクトリを指定する。

設定ファイルを作成します。
$ sudo vi /etc/tmpfiles.d/milter-manager.conf

設定ファイルを以下のように修正します。
milter-manager.conf
d /var/run/milter-manager 0755 milter-manager milter-manager

上記、設定ファイルを作成することで、再起動後、milter-managerのプロセスが起動していることを確認しました。
</pre>

<pre>
2.milter-managerのserviceファイル内のExecStartPreでディレクトリを作成する。

milter-managerのserviceファイルを編集します。
$ sudo vi /usr/lib/systemd/system/milter-manager.service

milter-manager.serviceファイルの[Service]セクションに以下を追記します。
ExecStartPre=/bin/mkdir /var/run/milter-manager

再起動後、/var/run/milter-managerは作成されておらず、/var/log/message上には、/var/run配下に
ディレクトリを作成する権限がなくmkdirが失敗した旨のメッセージが表示されていました。
</pre>

**Comment by okkez** [comment]
master の HEAD だと service ファイルの User, Group を root にしてあるので2の方法でいけるのではないでしょうか。

https://github.com/milter-manager/milter-manager/blob/master/data/systemd/redhat/milter-manager.service

**Comment by ohkubo** [comment]
> master の HEAD だと service ファイルの User, Group を root にしてあるので2の方法でいけるのではないでしょうか。
> 
> https://github.com/milter-manager/milter-manager/blob/master/data/systemd/redhat/milter-manager.service

加えて、以下の変更も必要ではないかと思います。

`/etc/sysconfig/milter-manager` を更新

https://github.com/milter-manager/milter-manager/blob/master/data/init.d/redhat/sysconfig/milter-manager

`/usr/lib/systemd/system/milter-manager.service` に追加

```
ExecStartPre=/bin/chown milter-manager:milter-manager /var/run/milter-manager
```

また、 `RuntimeDirectory=milter-manager` を使う方法もありそうですが、この場合のディレクトリは  **/var**/run/milter-manager ではなく /run/milter-manager になります。

**Comment by komainu8** [comment]
アドバイスありがとうございます。
ご指摘いただたいた通り、masterのHEADですと、User、Groupがrootとなっておりますので、2の方法でプロセスが起動するのですが、起動したプロセスはrootのプロセスとして動作してしまうため、セキュリティ上あまり好ましくないように思います。

/etc/sysconfig/milter-manager内でUSER、GROUPを指定する箇所がありましたので、ohokubo様ご提案の方法でプロセスの所有者が変更されるのかとも思いましたが、変わらずrootのままで動作しておりました。

今週はあまり時間が取れませんでしたが、来週はrootのプロセスで起動しないようにする方法を調査しつつ、1の方法で動作させたmilter-managerを簡単な設定で動作させようと考えております。

**Comment by okkez** [comment]
rootで起動したプロセスは何もしなくて、その後 fork したプロセスを milter-manager ユーザーに setuid(2) したものが、実際の処理を全て行ないます。
`ps aux | grep milter-manager` すると root ユーザーで起動しているプロセスと milter-manager ユーザーで起動しているプロセスが見つかるはずです。

このあたりは自分の理解も怪しいのですが、以下のように理解しています。

* root ユーザーで起動した方のプロセスはメールに関する処理は一切しません
* milter-manager ユーザーで起動しているプロセスだけがメールに関する処理をします
* root ユーザーで起動した方のプロセスにシグナルを送ると milter-manager ユーザーで起動しているプロセスにも伝わります
  * root ユーザーで起動した方のプロセスが milter-manager ユーザーで起動しているプロセスのPIDを知っている
* milter-manager ユーザーで起動しているプロセスから root ユーザーで起動しているプロセスに触る手段はありません(たぶん)

以上の通り、rootユーザーで起動する必要はありますし、rootユーザーで動作しているプロセスについてもセキュリティ上、特に問題ないように思えます。
なので、2の方針で実装を進めたいと考えています。

----

:memo: /var/run -> /run にシンボリックリンクされている環境とされていない環境があるので、/var/run -> /run のシンボリックリンクがある前提で考えると危険

* シンボリックリンクのない環境の例: lxc コンテナ
* シンボリックリンクのある環境の例: virtualbox 上の仮想マシン

**Comment by komainu8** [comment]
コメントありがとうございます。
1点、理解できない点がございましたので、質問させていただきたく思います。

上記のコメントでは、「rootユーザーで起動する必要がある」と記載されておりますが、特にrootユーザーでなければ実行できないようなことはしていないように見受けられました。不勉強で恐縮ですが、どのあたりの操作にroot権限が必要なのかご教授いただけないでしょうか？

また、ご指摘いただいた通り、rootユーザーとmilter-managerユーザーで動作しているプロセスが発見できました。

**Comment by okkez** [comment]
root ユーザーで起動しないと setuid(2), setgid(2) できないので `--user` オプションと `--group` オプションが使えなくなります。
sysvinit のときは root で起動して `--user`, `--group` で milter-manager ユーザーに切り替えていました。
そのため、なるべく以前と同じにしておきたいと考えています。

**Comment by komainu8** [comment]
ご回答ありがとうございます。理解いたしました。
2の方針で実装を進めるとのことですが、こちらは、私の方でserviceファイルを修正し、pull requestさせていただいてもよろしいでしょうか？

**Comment by okkez** [comment]
d73d035599d46f2d833156721c4219e303ab35e3 で作業済みのつもりです :bow:
何か問題があったらPRしてください。

**Comment by okkez** [comment]
動作確認OK

CentOS7 の仮想マシンを作ってRPMをインストール後、再起動し milter-manager プロセスが起動していることを確認した。
